CREATE TABLE PESSOA(
    ID NUMBER(5),
    NOME CHAR(20),
    IDADE NUMBER(5),
    GENERO CHAR(1),
    CEP NUMBER(10),
    SEGUIDORES NUMBER(10), -- numero de seguidores
    SALARIO NUMBER(10),
    PRIMARY KEY (ID)
);

CREATE TABLE NACIONALIDADE(
    PAIS CHAR(15),
    FK_PESSOA NUMBER(5),
    CONSTRAINT ID_NACIONALIDADE PRIMARY KEY (PAIS, FK_PESSOA),
    CONSTRAINT FK_PESSOA FOREIGN KEY (FK_PESSOA) REFERENCES PESSOA(ID)
);

CREATE TABLE CASTER(
    ID_CASTER NUMBER(5),
    FUNCAO CHAR(10),
    POPULARIDADE NUMBER(4, 2), -- Em porcentagem
    PRIMARY KEY(ID_CASTER),
    CONSTRAINT FK_CASTER FOREIGN KEY (ID_CASTER) REFERENCES PESSOA(ID)
);

CREATE TABLE CEO(
    ID_CEO NUMBER(5),
    NIVEL_FORMACAO CHAR(10),
    PRIMARY KEY (ID_CEO),
    CONSTRAINT FK_CEO FOREIGN KEY (ID_CEO) REFERENCES PESSOA(ID)
);

CREATE TABLE EQUIPE(
    ID_EQUIPE NUMBER(5),
    FK_CEO NUMBER(5),
    DATA_CRIACAO DATE,
    NOME CHAR (20),
    PRIMARY KEY (ID_EQUIPE),
    CONSTRAINT FK_EQUIPE_CEO FOREIGN KEY (FK_CEO) REFERENCES CEO(ID_CEO)
);

CREATE TABLE JOGADOR(
    ID_JOGADOR NUMBER(5),
    FUNCAO CHAR(6),
    EH_RESERVA CHAR(1) CHECK (EH_RESERVA = '1' OR EH_RESERVA = '0'),
    NICK_LOL CHAR(20) NOT NULL,
    FK_EQUIPE NUMBER(5),
    PRIMARY KEY (ID_JOGADOR),
    CONSTRAINT FK_JOGADOR_EQUIPE FOREIGN KEY (FK_EQUIPE) REFERENCES EQUIPE(ID_EQUIPE),
    CONSTRAINT FK_JOGADOR_PESSOA FOREIGN KEY (ID_JOGADOR) REFERENCES PESSOA(ID)
);

CREATE TABLE COACH(
    ID_COACH NUMBER(5),
    TIPO CHAR(10),
    FK_HEAD_COACH NUMBER(5),
    PRIMARY KEY (ID_COACH),
    CONSTRAINT FK_HEAD_COACH FOREIGN KEY (FK_HEAD_COACH) REFERENCES COACH(ID_COACH)
);

CREATE TABLE CAMPEONATO(
    ID_CAMPEONATO NUMBER(6),
    FK_MVP NUMBER(5),
    QNTD_EQUIPES NUMBER(3),
    PRIMARY KEY (ID_CAMPEONATO),
    CONSTRAINT FK_CAMPEONATO_MVP FOREIGN KEY (FK_MVP) REFERENCES JOGADOR(ID_JOGADOR)
);

CREATE TABLE PAUSE(
    ID_PAUSE NUMBER(6),
    PRIMARY KEY (ID_PAUSE)
);

CREATE TABLE PREMIACAO(
    POSICAO NUMBER(3),
    FK_CAMPEONATO NUMBER(5),
    VALOR NUMBER(15),
    CONSTRAINT ID_PREMIACAO PRIMARY KEY (POSICAO, FK_CAMPEONATO),
    CONSTRAINT FK_PREMIACAO_CAMPEONATO FOREIGN KEY (FK_CAMPEONATO) REFERENCES CAMPEONATO(ID_CAMPEONATO)
);

CREATE TABLE JOGO(
    FK_EQUIPE1 NUMBER(5),
    FK_EQUIPE2 NUMBER(5) NOT NULL,
    FK_CAMPEONATO NUMBER(5),
    DIA DATE,
    QNTD_TORCEDORES NUMBER(10),
    UNIQUE (DIA, FK_EQUIPE2),
    CONSTRAINT ID_JOGO PRIMARY KEY (FK_EQUIPE1, FK_CAMPEONATO, DIA),
    CONSTRAINT FK_JOGO_EQUIPE1 FOREIGN KEY (FK_EQUIPE1) REFERENCES EQUIPE(ID_EQUIPE),
    CONSTRAINT FK_JOGO_EQUIPE2 FOREIGN KEY (FK_EQUIPE2) REFERENCES EQUIPE(ID_EQUIPE),
    CONSTRAINT FK_JOGO_CAMPEONATO FOREIGN KEY (FK_CAMPEONATO) REFERENCES CAMPEONATO(ID_CAMPEONATO)
);

CREATE TABLE APRESENTA(
    FK_CAMPEONATO NUMBER(5),
    FK_CASTER NUMBER(5),
    CONSTRAINT ID_APRESENTA PRIMARY KEY (FK_CAMPEONATO, FK_CASTER),
    CONSTRAINT FK_APRESENTA_CAMPEONATO FOREIGN KEY (FK_CAMPEONATO) REFERENCES CAMPEONATO(ID_CAMPEONATO),
    CONSTRAINT FK_APRESENTA_CASTER FOREIGN KEY (FK_CASTER) REFERENCES CASTER(ID_CASTER)
);

CREATE TABLE OCORRE(
    FK_EQUIPE1 NUMBER(5),
    FK_EQUIPE2 NUMBER(5) NOT NULL,
    FK_CAMPEONATO NUMBER(5),
    DIA DATE,
    FK_PAUSE NUMBER(6),
    CONSTRAINT ID_OCORRE PRIMARY KEY (FK_EQUIPE1, FK_CAMPEONATO, DIA, FK_PAUSE),
    CONSTRAINT FK_OCORRE_JOGO FOREIGN KEY (FK_EQUIPE1, FK_CAMPEONATO, DIA) REFERENCES JOGO(FK_EQUIPE1, FK_CAMPEONATO, DIA),
    CONSTRAINT FK_OCORRE_PAUSE FOREIGN KEY (FK_PAUSE) REFERENCES PAUSE(ID_PAUSE)
);